---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  sudo: true

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - role[ruby_21]
      - recipe[backup::rvm_install]
    attributes:
      backup:
        rvm_ruby_string: "ruby-2.1.9@backup"
